// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// match_substrings
std::map<int, std::unordered_set<int> > match_substrings(CharacterVector master, CharacterVector comparison, int k);
RcppExport SEXP _stringcandidates_match_substrings(SEXP masterSEXP, SEXP comparisonSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type master(masterSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type comparison(comparisonSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(match_substrings(master, comparison, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stringcandidates_match_substrings", (DL_FUNC) &_stringcandidates_match_substrings, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_stringcandidates(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
