// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lookup_env
Environment lookup_env(List cond, std::string sex, std::string starter);
RcppExport SEXP _stringcandidates_lookup_env(SEXP condSEXP, SEXP sexSEXP, SEXP starterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cond(condSEXP);
    Rcpp::traits::input_parameter< std::string >::type sex(sexSEXP);
    Rcpp::traits::input_parameter< std::string >::type starter(starterSEXP);
    rcpp_result_gen = Rcpp::wrap(lookup_env(cond, sex, starter));
    return rcpp_result_gen;
END_RCPP
}
// interp
std::string interp(List conds, std::string sex, std::string starter, NumericVector context_sizes, NumericVector weights);
RcppExport SEXP _stringcandidates_interp(SEXP condsSEXP, SEXP sexSEXP, SEXP starterSEXP, SEXP context_sizesSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type conds(condsSEXP);
    Rcpp::traits::input_parameter< std::string >::type sex(sexSEXP);
    Rcpp::traits::input_parameter< std::string >::type starter(starterSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type context_sizes(context_sizesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(interp(conds, sex, starter, context_sizes, weights));
    return rcpp_result_gen;
END_RCPP
}
// match_substrings
std::map<int, std::unordered_set<int> > match_substrings(CharacterVector master, CharacterVector comparison, int k);
RcppExport SEXP _stringcandidates_match_substrings(SEXP masterSEXP, SEXP comparisonSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type master(masterSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type comparison(comparisonSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(match_substrings(master, comparison, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stringcandidates_lookup_env", (DL_FUNC) &_stringcandidates_lookup_env, 3},
    {"_stringcandidates_interp", (DL_FUNC) &_stringcandidates_interp, 5},
    {"_stringcandidates_match_substrings", (DL_FUNC) &_stringcandidates_match_substrings, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_stringcandidates(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
