# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lookup_env <- function(cond, starter) {
    .Call('_stringcandidates_lookup_env', PACKAGE = 'stringcandidates', cond, starter)
}

interp <- function(conds, starter, context_sizes, weights, n) {
    .Call('_stringcandidates_interp', PACKAGE = 'stringcandidates', conds, starter, context_sizes, weights, n)
}

substitution <- function(x) {
    .Call('_stringcandidates_substitution', PACKAGE = 'stringcandidates', x)
}

match_substrings <- function(master, comparison, k) {
    .Call('_stringcandidates_match_substrings', PACKAGE = 'stringcandidates', master, comparison, k)
}

