# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lookup_env <- function(cond, sex, starter) {
    .Call('_stringcandidates_lookup_env', PACKAGE = 'stringcandidates', cond, sex, starter)
}

interp <- function(conds, sex, starter, context_sizes, weights) {
    .Call('_stringcandidates_interp', PACKAGE = 'stringcandidates', conds, sex, starter, context_sizes, weights)
}

substitution <- function(x) {
    .Call('_stringcandidates_substitution', PACKAGE = 'stringcandidates', x)
}

match_substrings <- function(master, comparison, k) {
    .Call('_stringcandidates_match_substrings', PACKAGE = 'stringcandidates', master, comparison, k)
}

