# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

match_substrings <- function(master, comparison, k) {
    .Call('_stringcandidates_match_substrings', PACKAGE = 'stringcandidates', master, comparison, k)
}

match_substrings2 <- function(master, comparison, k) {
    .Call('_stringcandidates_match_substrings2', PACKAGE = 'stringcandidates', master, comparison, k)
}

